	// cfgVehicles

	class SIL_STALKER_Military_Base_F: SIL_STALKER_Base_F
	{
		editorSubcategory = "SIL_STALKER_Subcategory_Military_Men";
		scope = 1;
		side = FACTION_MILITARY_SIDE; // 0 = OPFOR, 1 = BLUFOR, 2 = IND
		FACTION_MILITARY;
		identityTypes[]=
		{
			"Male01ENG",
			"WhiteHead_01",
			"NoGlasses"
		};
	};

	class SIL_STALKER_Military_Rifleman_1_F: SIL_STALKER_Military_Base_F
	{
		PREVIEW(SIL_STALKER_Military_Rifleman_1_F);
		displayName = "Rifleman";
		uniformClass = "SCE_Military_3";
		scope = 2;
		backpack = "CUP_B_Kombat_Radio_Olive";
		identityTypes[]=
		{
			"Male03ENG",
			"WhiteHead_04",
			"NoGlasses"
		};
		linkedItems[]=
		{
			"CUP_H_RUS_6B27",
			"SCE_G_CN3P",
			"CUP_V_B_RRV_Scout3_GRN",
			LOADOUT_ITEMS_FULL
		};
		respawnLinkedItems[]=
		{
			"CUP_H_RUS_6B27",
			"SCE_G_CN3P",
			"CUP_V_B_RRV_Scout3_GRN",
			LOADOUT_ITEMS_FULL
		};
		weapons[]=
		{
			"CUP_arifle_AK74M_1p63",
			"CUP_hgun_Compact",
			LOADOUT_WEAPONS_DEFAULT
		};
		respawnWeapons[]=
		{
			"CUP_arifle_AK74M_1p63",
			"CUP_hgun_Compact",
			LOADOUT_WEAPONS_DEFAULT
		};
		magazines[]=
		{
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_10Rnd_9x19_Compact",
			"CUP_10Rnd_9x19_Compact",
			LOADOUT_MAGAZINES_FULL
		};
		respawnMagazines[]=
		{
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_10Rnd_9x19_Compact",
			"CUP_10Rnd_9x19_Compact",
			LOADOUT_MAGAZINES_FULL
		};
	};
	class SIL_STALKER_Military_Rifleman_2_F: SIL_STALKER_Military_Base_F
	{
		PREVIEW(SIL_STALKER_Military_Rifleman_2_F);
		displayName = "Rifleman (Alternate)";
		uniformClass = "SCE_Military_3";
		scope = 2;
		backpack = "CUP_B_Kombat_Radio_Olive";
		identityTypes[]=
		{
			"Male08ENG",
			"WhiteHead_07",
			"NoGlasses"
		};
		linkedItems[]=
		{
			"CUP_H_RUS_6B27",
			"SCE_G_M40_1",
			"CUP_V_B_RRV_Scout",
			LOADOUT_ITEMS_FULL
		};
		respawnLinkedItems[]=
		{
			"CUP_H_RUS_6B27",
			"SCE_G_M40_1",
			"CUP_V_B_RRV_Scout",
			LOADOUT_ITEMS_FULL
		};
		weapons[]=
		{
			"CUP_arifle_OTS14_GROZA_762_Grip",
			"CUP_hgun_Compact",
			LOADOUT_WEAPONS_DEFAULT
		};
		respawnWeapons[]=
		{
			"CUP_arifle_OTS14_GROZA_762_Grip",
			"CUP_hgun_Compact",
			LOADOUT_WEAPONS_DEFAULT
		};
		magazines[]=
		{
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_10Rnd_9x19_Compact",
			"CUP_10Rnd_9x19_Compact",
			LOADOUT_MAGAZINES_FULL
		};
		respawnMagazines[]=
		{
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_10Rnd_9x19_Compact",
			"CUP_10Rnd_9x19_Compact",
			LOADOUT_MAGAZINES_FULL
		};
	};
	class SIL_STALKER_Military_Rifleman_Light_F: SIL_STALKER_Military_Base_F
	{
		PREVIEW(SIL_STALKER_Military_Rifleman_Light_F);
		displayName = "Rifleman (Light)";
		uniformClass = "SCE_Military_3";
		scope = 2;
		backpack = "CUP_B_CivPack_WDL";
		identityTypes[]=
		{
			"Male06ENG",
			"WhiteHead_02",
			"NoGlasses"
		};
		linkedItems[]=
		{
			"CUP_H_CZ_Hat02",
			"SCE_G_CN3P",
			"CUP_V_B_RRV_Scout2",
			LOADOUT_ITEMS_FULL
		};
		respawnLinkedItems[]=
		{
			"CUP_H_CZ_Hat02",
			"SCE_G_CN3P",
			"CUP_V_B_RRV_Scout2",
			LOADOUT_ITEMS_FULL
		};
		weapons[]=
		{
			"CUP_arifle_AKS74U",
			"CUP_hgun_Compact",
			LOADOUT_WEAPONS_DEFAULT
		};
		respawnWeapons[]=
		{
			"CUP_arifle_AKS74U",
			"CUP_hgun_Compact",
			LOADOUT_WEAPONS_DEFAULT
		};
		magazines[]=
		{
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_10Rnd_9x19_Compact",
			"CUP_10Rnd_9x19_Compact",
			LOADOUT_MAGAZINES_FULL
		};
		respawnMagazines[]=
		{
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_10Rnd_9x19_Compact",
			"CUP_10Rnd_9x19_Compact",
			LOADOUT_MAGAZINES_FULL
		};
	};
	class SIL_STALKER_Military_Medic_F: SIL_STALKER_Military_Base_F
	{
		PREVIEW(SIL_STALKER_Military_Medic_F);
		displayName = "Medic";
		uniformClass = "SCE_Military_3";
		scope = 2;
		UNIT_ROLE_MEDIC;
		backpack = "CUP_B_RUS_Backpack";
		identityTypes[]=
		{
			"Male06ENG",
			"WhiteHead_02",
			"NoGlasses"
		};
		linkedItems[]=
		{
			"CUP_H_SLA_BeretRed",
			"CUP_FR_NeckScarf4",
			"CUP_V_B_RRV_Medic",
			LOADOUT_ITEMS_FULL
		};
		respawnLinkedItems[]=
		{
			"CUP_H_SLA_BeretRed",
			"CUP_FR_NeckScarf4",
			"CUP_V_B_RRV_Medic",
			LOADOUT_ITEMS_FULL
		};
		weapons[]=
		{
			"CUP_arifle_AKS74U",
			"CUP_hgun_Compact",
			LOADOUT_WEAPONS_DEFAULT
		};
		respawnWeapons[]=
		{
			"CUP_arifle_AKS74U",
			"CUP_hgun_Compact",
			LOADOUT_WEAPONS_DEFAULT
		};
		magazines[]=
		{
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_10Rnd_9x19_Compact",
			"CUP_10Rnd_9x19_Compact",
			LOADOUT_MAGAZINES_FULL
		};
		respawnMagazines[]=
		{
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_10Rnd_9x19_Compact",
			"CUP_10Rnd_9x19_Compact",
			LOADOUT_MAGAZINES_FULL
		};
	};
	class SIL_STALKER_Military_Sharpshooter_F: SIL_STALKER_Military_Base_F
	{
		PREVIEW(SIL_STALKER_Military_Sharpshooter_F);
		displayName = "Sharpshooter Ranger";
		uniformClass = "SCE_Military_3";
		scope = 2;
		backpack = "CUP_B_ACRPara_m95";
		identityTypes[]=
		{
			"Male08ENG",
			"WhiteHead_04",
			"NoGlasses"
		};
		linkedItems[]=
		{
			"CUP_H_CZ_Patrol_Cap",
			"SCE_G_CN3P",
			"CUP_V_B_RRV_Light",
			LOADOUT_ITEMS_FULL
		};
		respawnLinkedItems[]=
		{
			"CUP_H_CZ_Patrol_Cap",
			"SCE_G_CN3P",
			"CUP_V_B_RRV_Light",
			LOADOUT_ITEMS_FULL
		};
		weapons[]=
		{
			"SIL_STALKER_srifle_SVD_wdl_ghillie_pso",
			"CUP_hgun_Compact",
			LOADOUT_WEAPONS_DEFAULT
		};
		respawnWeapons[]=
		{
			"SIL_STALKER_srifle_SVD_wdl_ghillie_pso",
			"CUP_hgun_Compact",
			LOADOUT_WEAPONS_DEFAULT
		};
		magazines[]=
		{
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_9x19_Compact",
			"CUP_10Rnd_9x19_Compact",
			LOADOUT_MAGAZINES_FULL
		};
		respawnMagazines[]=
		{
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_9x19_Compact",
			"CUP_10Rnd_9x19_Compact",
			LOADOUT_MAGAZINES_FULL
		};
	};
	class SIL_STALKER_Military_Engineer_F: SIL_STALKER_Military_Base_F
	{
		PREVIEW(SIL_STALKER_Military_Engineer_F);
		displayName = "Engineer";
		uniformClass = "SCE_Military_3";
		scope = 2;
		UNIT_ROLE_ENGINEER;
		backpack = "CUP_B_ACRPara_m95";
		identityTypes[]=
		{
			"Male05ENG",
			"WhiteHead_12",
			"NoGlasses"
		};
		linkedItems[]=
		{
			"CUP_H_RUS_6B27",
			"SCE_G_M40_1",
			"CUP_V_B_RRV_MG_GRN",
			LOADOUT_ITEMS_FULL
		};
		respawnLinkedItems[]=
		{
			"CUP_H_RUS_6B27",
			"SCE_G_M40_1",
			"CUP_V_B_RRV_MG_GRN",
			LOADOUT_ITEMS_FULL
		};
		weapons[]=
		{
			"CUP_smg_saiga9",
			"CUP_hgun_Compact",
			LOADOUT_WEAPONS_DEFAULT
		};
		respawnWeapons[]=
		{
			"CUP_smg_saiga9",
			"CUP_hgun_Compact",
			LOADOUT_WEAPONS_DEFAULT
		};
		magazines[]=
		{
			"CUP_30Rnd_9x19_Vityaz",
			"CUP_30Rnd_9x19_Vityaz",
			"CUP_30Rnd_9x19_Vityaz",
			"CUP_30Rnd_9x19_Vityaz",
			"CUP_30Rnd_9x19_Vityaz",
			"CUP_30Rnd_9x19_Vityaz",
			"CUP_10Rnd_9x19_Compact",
			"CUP_10Rnd_9x19_Compact",
			LOADOUT_MAGAZINES_FULL
		};
		respawnMagazines[]=
		{
			"CUP_30Rnd_9x19_Vityaz",
			"CUP_30Rnd_9x19_Vityaz",
			"CUP_30Rnd_9x19_Vityaz",
			"CUP_30Rnd_9x19_Vityaz",
			"CUP_30Rnd_9x19_Vityaz",
			"CUP_30Rnd_9x19_Vityaz",
			"CUP_10Rnd_9x19_Compact",
			"CUP_10Rnd_9x19_Compact",
			LOADOUT_MAGAZINES_FULL
		};
	};
	class SIL_STALKER_Military_Autorifleman_F: SIL_STALKER_Military_Base_F
	{
		PREVIEW(SIL_STALKER_Military_Autorifleman_F);
		displayName = "Autorifleman";
		uniformClass = "SCE_Military_1";
		scope = 2;
		identityTypes[]=
		{
			"Male02ENG",
			"WhiteHead_11",
			"NoGlasses"
		};
		linkedItems[]=
		{
			"SCE_Exo_Helmet_Military",
			"CAU_G_CBRN_m04_blk_hood",
			"SCE_Exo2G_Military",
			LOADOUT_ITEMS_FULL
		};
		respawnLinkedItems[]=
		{
			"SCE_Exo_Helmet_Military",
			"CAU_G_CBRN_m04_blk_hood",
			"SCE_Exo2G_Military",
			LOADOUT_ITEMS_FULL
		};
		weapons[]=
		{
			"CUP_lmg_Pecheneg_top_rail_B50_vfg",
			LOADOUT_WEAPONS_DEFAULT
		};
		respawnWeapons[]=
		{
			"CUP_lmg_Pecheneg_top_rail_B50_vfg",
			LOADOUT_WEAPONS_DEFAULT
		};
		magazines[]=
		{
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
			LOADOUT_MAGAZINES_FULL
		};
		respawnMagazines[]=
		{
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
			LOADOUT_MAGAZINES_FULL
		};
	};
	class SIL_STALKER_Military_Pilot_F: SIL_STALKER_Military_Base_F
	{
		PREVIEW(SIL_STALKER_Military_Pilot_F);
		displayName = "Pilot";
		uniformClass = "SIL_STALKER_U_USArmy_PilotOverall";
		scope = 2;
		identityTypes[]=
		{
			"Male04ENG",
			"WhiteHead_08",
			"NoGlasses"
		};
		linkedItems[]=
		{
			"CUP_H_RUS_6B47_headset",
			"CUP_Vest_RUS_6B45_Sh117_Green",
			LOADOUT_ITEMS_FULL
		};
		respawnLinkedItems[]=
		{
			"CUP_H_RUS_6B47_headset",
			"CUP_Vest_RUS_6B45_Sh117_Green",
			LOADOUT_ITEMS_FULL
		};
		weapons[]=
		{
			LOADOUT_WEAPONS_DEFAULT
		};
		respawnWeapons[]=
		{
			LOADOUT_WEAPONS_DEFAULT
		};
		magazines[]={};
		respawnMagazines[]={};
	};

	/* SEVA Units */
	class SIL_STALKER_Military_SEVA_Base_F: SIL_STALKER_Military_Base_F
	{
		uniformClass = "SCE_Military_CBRN";
		backpack = "SCE_B_SEVA_Military";
		editorSubcategory = "SIL_STALKER_Subcategory_Military_Men_SEVA";
		scope = 1;
		linkedItems[]=
		{
			"SCE_H_SEVA_Military",
			"SCE_G_SEVA_HELMET_VISOR",
			"SCE_V_SEVA_Military",
			LOADOUT_ITEMS_FULL
		};
		respawnLinkedItems[]=
		{
			"SCE_H_SEVA_Military",
			"SCE_G_SEVA_HELMET_VISOR",
			"SCE_V_SEVA_Military",
			LOADOUT_ITEMS_FULL
		};
	};
	class SIL_STALKER_Military_SEVA_Rifleman_1_F: SIL_STALKER_Military_SEVA_Base_F
	{
		PREVIEW(SIL_STALKER_Military_SEVA_Rifleman_1_F);
		displayName = "Rifleman";
		scope = 2;
		identityTypes[]=
		{
			"Male02ENG",
			"WhiteHead_04",
			"NoGlasses"
		};
		weapons[]=
		{
			"CUP_arifle_AK74M",
			"CUP_hgun_Compact",
			LOADOUT_WEAPONS_DEFAULT
		};
		respawnWeapons[]=
		{
			"CUP_arifle_AK74M",
			"CUP_hgun_Compact",
			LOADOUT_WEAPONS_DEFAULT
		};
		magazines[]=
		{
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_10Rnd_9x19_Compact",
			"CUP_10Rnd_9x19_Compact",
			LOADOUT_MAGAZINES_FULL
		};
		respawnMagazines[]=
		{
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_10Rnd_9x19_Compact",
			"CUP_10Rnd_9x19_Compact",
			LOADOUT_MAGAZINES_FULL
		};
	};
	class SIL_STALKER_Military_SEVA_Rifleman_2_F: SIL_STALKER_Military_SEVA_Base_F
	{
		PREVIEW(SIL_STALKER_Military_SEVA_Rifleman_2_F);
		displayName = "Rifleman (Alternate)";
		scope = 2;
		identityTypes[]=
		{
			"Male04ENG",
			"WhiteHead_06",
			"NoGlasses"
		};
		weapons[]=
		{
			"CUP_arifle_AS_VAL",
			"CUP_hgun_Compact",
			LOADOUT_WEAPONS_DEFAULT
		};
		respawnWeapons[]=
		{
			"CUP_arifle_AS_VAL",
			"CUP_hgun_Compact",
			LOADOUT_WEAPONS_DEFAULT
		};
		magazines[]=
		{
			"CUP_20Rnd_9x39_SP5_VSS_M",
			"CUP_20Rnd_9x39_SP5_VSS_M",
			"CUP_20Rnd_9x39_SP5_VSS_M",
			"CUP_20Rnd_9x39_SP5_VSS_M",
			"CUP_20Rnd_9x39_SP5_VSS_M",
			"CUP_20Rnd_9x39_SP5_VSS_M",
			"CUP_10Rnd_9x19_Compact",
			"CUP_10Rnd_9x19_Compact",
			LOADOUT_MAGAZINES_FULL
		};
		respawnMagazines[]=
		{
			"CUP_20Rnd_9x39_SP5_VSS_M",
			"CUP_20Rnd_9x39_SP5_VSS_M",
			"CUP_20Rnd_9x39_SP5_VSS_M",
			"CUP_20Rnd_9x39_SP5_VSS_M",
			"CUP_20Rnd_9x39_SP5_VSS_M",
			"CUP_20Rnd_9x39_SP5_VSS_M",
			"CUP_10Rnd_9x19_Compact",
			"CUP_10Rnd_9x19_Compact",
			LOADOUT_MAGAZINES_FULL
		};
	};
	class SIL_STALKER_Military_SEVA_Rifleman_Light_F: SIL_STALKER_Military_SEVA_Base_F
	{
		PREVIEW(SIL_STALKER_Military_SEVA_Rifleman_Light_F);
		displayName = "Rifleman (Light)";
		scope = 2;
		identityTypes[]=
		{
			"Male06ENG",
			"WhiteHead_02",
			"NoGlasses"
		};
		weapons[]=
		{
			"CUP_arifle_AKS74U",
			"CUP_hgun_Compact",
			LOADOUT_WEAPONS_DEFAULT
		};
		respawnWeapons[]=
		{
			"CUP_arifle_AKS74U",
			"CUP_hgun_Compact",
			LOADOUT_WEAPONS_DEFAULT
		};
		magazines[]=
		{
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_10Rnd_9x19_Compact",
			"CUP_10Rnd_9x19_Compact",
			LOADOUT_MAGAZINES_FULL
		};
		respawnMagazines[]=
		{
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_10Rnd_9x19_Compact",
			"CUP_10Rnd_9x19_Compact",
			LOADOUT_MAGAZINES_FULL
		};
	};
	class SIL_STALKER_Military_SEVA_Medic_F: SIL_STALKER_Military_SEVA_Base_F
	{
		PREVIEW(SIL_STALKER_Military_SEVA_Medic_F);
		displayName = "Medic";
		scope = 2;
		UNIT_ROLE_MEDIC;
		identityTypes[]=
		{
			"Male07ENG",
			"WhiteHead_03",
			"NoGlasses"
		};
		weapons[]=
		{
			"CUP_arifle_AK74M",
			"CUP_hgun_Compact",
			LOADOUT_WEAPONS_DEFAULT
		};
		respawnWeapons[]=
		{
			"CUP_arifle_AK74M",
			"CUP_hgun_Compact",
			LOADOUT_WEAPONS_DEFAULT
		};
		magazines[]=
		{
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_10Rnd_9x19_Compact",
			"CUP_10Rnd_9x19_Compact",
			LOADOUT_MAGAZINES_FULL
		};
		respawnMagazines[]=
		{
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_10Rnd_9x19_Compact",
			"CUP_10Rnd_9x19_Compact",
			LOADOUT_MAGAZINES_FULL
		};
	};
	class SIL_STALKER_Military_SEVA_Sharpshooter_F: SIL_STALKER_Military_SEVA_Base_F
	{
		PREVIEW(SIL_STALKER_Military_SEVA_Sharpshooter_F);
		displayName = "Sharpshooter";
		scope = 2;
		identityTypes[]=
		{
			"Male08ENG",
			"WhiteHead_02",
			"NoGlasses"
		};
		weapons[]=
		{
			"CUP_srifle_SVD",
			"CUP_hgun_Compact",
			LOADOUT_WEAPONS_DEFAULT
		};
		respawnWeapons[]=
		{
			"CUP_srifle_SVD",
			"CUP_hgun_Compact",
			LOADOUT_WEAPONS_DEFAULT
		};
		magazines[]=
		{
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_9x19_Compact",
			"CUP_10Rnd_9x19_Compact",
			LOADOUT_MAGAZINES_FULL
		};
		respawnMagazines[]=
		{
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_9x19_Compact",
			"CUP_10Rnd_9x19_Compact",
			LOADOUT_MAGAZINES_FULL
		};
	};
	class SIL_STALKER_Military_SEVA_Engineer_F: SIL_STALKER_Military_SEVA_Base_F
	{
		PREVIEW(SIL_STALKER_Military_SEVA_Engineer_F);
		displayName = "Engineer";
		scope = 2;
		UNIT_ROLE_ENGINEER;
		identityTypes[]=
		{
			"Male09ENG",
			"WhiteHead_05",
			"NoGlasses"
		};
		weapons[]=
		{
			"CUP_smg_saiga9",
			"CUP_hgun_Compact",
			LOADOUT_WEAPONS_DEFAULT
		};
		respawnWeapons[]=
		{
			"CUP_smg_saiga9",
			"CUP_hgun_Compact",
			LOADOUT_WEAPONS_DEFAULT
		};
		magazines[]=
		{
			"CUP_30Rnd_9x19_Vityaz",
			"CUP_30Rnd_9x19_Vityaz",
			"CUP_30Rnd_9x19_Vityaz",
			"CUP_30Rnd_9x19_Vityaz",
			"CUP_30Rnd_9x19_Vityaz",
			"CUP_30Rnd_9x19_Vityaz",
			"CUP_10Rnd_9x19_Compact",
			"CUP_10Rnd_9x19_Compact",
			LOADOUT_MAGAZINES_FULL
		};
		respawnMagazines[]=
		{
			"CUP_30Rnd_9x19_Vityaz",
			"CUP_30Rnd_9x19_Vityaz",
			"CUP_30Rnd_9x19_Vityaz",
			"CUP_30Rnd_9x19_Vityaz",
			"CUP_30Rnd_9x19_Vityaz",
			"CUP_30Rnd_9x19_Vityaz",
			"CUP_10Rnd_9x19_Compact",
			"CUP_10Rnd_9x19_Compact",
			LOADOUT_MAGAZINES_FULL
		};
	};

	/* No PPE Units */
	class SIL_STALKER_Military_NoPPE_Rifleman_1_F: SIL_STALKER_Military_Rifleman_1_F
	{
		PREVIEW(SIL_STALKER_Military_NoPPE_Rifleman_1_F);
		editorSubcategory = "SIL_STALKER_Subcategory_Military_Men_NoPPE";
		scope = 2;
		linkedItems[]=
		{
			"CUP_H_RUS_6B27",
			"CUP_V_B_RRV_Scout3_GRN",
			LOADOUT_ITEMS_FULL
		};
		respawnLinkedItems[]=
		{
			"CUP_H_RUS_6B27",
			"CUP_V_B_RRV_Scout3_GRN",
			LOADOUT_ITEMS_FULL
		};
	};
	class SIL_STALKER_Military_NoPPE_Rifleman_2_F: SIL_STALKER_Military_Rifleman_2_F
	{
		PREVIEW(SIL_STALKER_Military_NoPPE_Rifleman_2_F);
		editorSubcategory = "SIL_STALKER_Subcategory_Military_Men_NoPPE";
		scope = 2;
		linkedItems[]=
		{
			"CUP_H_RUS_6B27",
			"CUP_V_B_RRV_Scout",
			LOADOUT_ITEMS_FULL
		};
		respawnLinkedItems[]=
		{
			"CUP_H_RUS_6B27",
			"CUP_V_B_RRV_Scout",
			LOADOUT_ITEMS_FULL
		};
	};
	class SIL_STALKER_Military_NoPPE_Rifleman_Light_F: SIL_STALKER_Military_Rifleman_Light_F
	{
		PREVIEW(SIL_STALKER_Military_NoPPE_Rifleman_Light_F);
		editorSubcategory = "SIL_STALKER_Subcategory_Military_Men_NoPPE";
		scope = 2;
		linkedItems[]=
		{
			"CUP_H_CZ_Hat02",
			"CUP_V_B_RRV_Scout2",
			LOADOUT_ITEMS_FULL
		};
		respawnLinkedItems[]=
		{
			"CUP_H_CZ_Hat02",
			"CUP_V_B_RRV_Scout2",
			LOADOUT_ITEMS_FULL
		};
	};
	class SIL_STALKER_Military_NoPPE_Medic_F: SIL_STALKER_Military_Medic_F
	{
		PREVIEW(SIL_STALKER_Military_NoPPE_Medic_F);
		editorSubcategory = "SIL_STALKER_Subcategory_Military_Men_NoPPE";
		scope = 2;
		linkedItems[]=
		{
			"CUP_H_SLA_BeretRed",
			"CUP_FR_NeckScarf4",
			"CUP_V_B_RRV_Medic",
			LOADOUT_ITEMS_FULL
		};
		respawnLinkedItems[]=
		{
			"CUP_H_SLA_BeretRed",
			"CUP_FR_NeckScarf4",
			"CUP_V_B_RRV_Medic",
			LOADOUT_ITEMS_FULL
		};
	};
	class SIL_STALKER_Military_NoPPE_Sharpshooter_F: SIL_STALKER_Military_Sharpshooter_F
	{
		PREVIEW(SIL_STALKER_Military_NoPPE_Sharpshooter_F);
		editorSubcategory = "SIL_STALKER_Subcategory_Military_Men_NoPPE";
		scope = 2;
		linkedItems[]=
		{
			"CUP_H_CZ_Patrol_Cap",
			"CUP_V_B_RRV_Light",
			LOADOUT_ITEMS_FULL
		};
		respawnLinkedItems[]=
		{
			"CUP_H_CZ_Patrol_Cap",
			"CUP_V_B_RRV_Light",
			LOADOUT_ITEMS_FULL
		};
	};
	class SIL_STALKER_Military_NoPPE_Engineer_F: SIL_STALKER_Military_Engineer_F
	{
		PREVIEW(SIL_STALKER_Military_NoPPE_Engineer_F);
		editorSubcategory = "SIL_STALKER_Subcategory_Military_Men_NoPPE";
		scope = 2;
		linkedItems[]=
		{
			"CUP_H_RUS_6B27",
			"CUP_V_B_RRV_MG_GRN",
			LOADOUT_ITEMS_FULL
		};
		respawnLinkedItems[]=
		{
			"CUP_H_RUS_6B27",
			"CUP_V_B_RRV_MG_GRN",
			LOADOUT_ITEMS_FULL
		};
	};