	// cfgVehicles

	class SIL_STALKER_Bandit_Base_F: SIL_STALKER_Base_F
	{
		editorSubcategory = "SIL_STALKER_Subcategory_Bandits_Men";
		scope = 1;
		side = FACTION_BANDITS_SIDE; // 0 = OPFOR, 1 = BLUFOR, 2 = IND
		FACTION_BANDITS;
		identityTypes[]=
		{
			"Male01ENG",
			"WhiteHead_01",
			"NoGlasses"
		};
	};

	class SIL_STALKER_Bandit_Rifleman_1_F: SIL_STALKER_Bandit_Base_F
	{
		PREVIEW(SIL_STALKER_Bandit_Rifleman_1_F);
		displayName = "Rifleman";
		uniformClass = "SCE_Bandit_Rags_2_1";
		scope = 2;
		identityTypes[]=
		{
			"Male01ENG",
			"WhiteHead_01",
			"NoGlasses"
		};
		linkedItems[]=
		{
			"SE_Ushanka",
			"G_Balaclava_blk",
			"SCE_Coat_Short_2",
			LOADOUT_ITEMS_FULL
		};
		respawnLinkedItems[]=
		{
			"SE_Ushanka",
			"G_Balaclava_blk",
			"SCE_Coat_Short_2",
			LOADOUT_ITEMS_FULL
		};
		weapons[]=
		{
			"CUP_SKS",
			LOADOUT_WEAPONS_DEFAULT
		};
		respawnWeapons[]=
		{
			"CUP_SKS",
			LOADOUT_WEAPONS_DEFAULT
		};
		magazines[]=
		{
			"CUP_10Rnd_762x39_SKS_M",
			"CUP_10Rnd_762x39_SKS_M",
			"CUP_10Rnd_762x39_SKS_M",
			"CUP_10Rnd_762x39_SKS_M",
			"CUP_10Rnd_762x39_SKS_M",
			"CUP_10Rnd_762x39_SKS_M",
			LOADOUT_MAGAZINES_FULL
		};
		respawnMagazines[]=
		{
			"CUP_10Rnd_762x39_SKS_M",
			"CUP_10Rnd_762x39_SKS_M",
			"CUP_10Rnd_762x39_SKS_M",
			"CUP_10Rnd_762x39_SKS_M",
			"CUP_10Rnd_762x39_SKS_M",
			"CUP_10Rnd_762x39_SKS_M",
			LOADOUT_MAGAZINES_FULL
		};
	};
	class SIL_STALKER_Bandit_Rifleman_2_F: SIL_STALKER_Bandit_Base_F
	{
		PREVIEW(SIL_STALKER_Bandit_Rifleman_2_F);
		displayName = "Rifleman (Alternate)";
		uniformClass = "SCE_Bandit_Rags_1_2";
		scope = 2;
		identityTypes[]=
		{
			"Male03ENG",
			"WhiteHead_05",
			"NoGlasses"
		};
		linkedItems[]=
		{
			"armst_Hood_band_3",
			"G_Bandanna_blk",
			"SCE_Coat_Short_3",
			LOADOUT_ITEMS_FULL
		};
		respawnLinkedItems[]=
		{
			"armst_Hood_band_3",
			"G_Bandanna_blk",
			"SCE_Coat_Short_3",
			LOADOUT_ITEMS_FULL
		};
		weapons[]=
		{
			"CUP_arifle_AKM",
			LOADOUT_WEAPONS_DEFAULT
		};
		respawnWeapons[]=
		{
			"CUP_arifle_AKM",
			LOADOUT_WEAPONS_DEFAULT
		};
		magazines[]=
		{
			"CUP_30Rnd_762x39_AK47_bakelite_M",
			"CUP_30Rnd_762x39_AK47_bakelite_M",
			"CUP_30Rnd_762x39_AK47_bakelite_M",
			"CUP_30Rnd_762x39_AK47_bakelite_M",
			"CUP_30Rnd_762x39_AK47_bakelite_M",
			"CUP_30Rnd_762x39_AK47_bakelite_M",
			LOADOUT_MAGAZINES_FULL
		};
		respawnMagazines[]=
		{
			"CUP_30Rnd_762x39_AK47_bakelite_M",
			"CUP_30Rnd_762x39_AK47_bakelite_M",
			"CUP_30Rnd_762x39_AK47_bakelite_M",
			"CUP_30Rnd_762x39_AK47_bakelite_M",
			"CUP_30Rnd_762x39_AK47_bakelite_M",
			"CUP_30Rnd_762x39_AK47_bakelite_M",
			LOADOUT_MAGAZINES_FULL
		};
	};
	class SIL_STALKER_Bandit_Rifleman_Light_F: SIL_STALKER_Bandit_Base_F
	{
		PREVIEW(SIL_STALKER_Bandit_Rifleman_Light_F);
		displayName = "Rifleman (Light)";
		uniformClass = "SCE_Bandit_Rags_1_1";
		scope = 2;
		identityTypes[]=
		{
			"Male05ENG",
			"WhiteHead_07",
			"NoGlasses"
		};
		linkedItems[]=
		{
			"armst_Hood_mid_loner1",
			"G_Balaclava_blk",
			"SCE_Sunrise_Bandit",
			LOADOUT_ITEMS_FULL
		};
		respawnLinkedItems[]=
		{
			"armst_Hood_mid_loner1",
			"G_Balaclava_blk",
			"SCE_Sunrise_Bandit",
			LOADOUT_ITEMS_FULL
		};
		weapons[]=
		{
			"CUP_sgun_CZ584",
			LOADOUT_WEAPONS_DEFAULT
		};
		respawnWeapons[]=
		{
			"CUP_sgun_CZ584",
			LOADOUT_WEAPONS_DEFAULT
		};
		magazines[]=
		{
			"CUP_1Rnd_12Gauge_Pellets_No00_Buck",
			"CUP_1Rnd_12Gauge_Pellets_No00_Buck",
			"CUP_1Rnd_12Gauge_Pellets_No00_Buck",
			"CUP_1Rnd_12Gauge_Pellets_No00_Buck",
			"CUP_1Rnd_12Gauge_Pellets_No00_Buck",
			"CUP_1Rnd_12Gauge_Pellets_No00_Buck",
			"CUP_1Rnd_12Gauge_Pellets_No00_Buck",
			"CUP_1Rnd_12Gauge_Pellets_No00_Buck",
			"CUP_1Rnd_12Gauge_Pellets_No00_Buck",
			"CUP_1Rnd_12Gauge_Pellets_No00_Buck",
			"CUP_1Rnd_12Gauge_Pellets_No00_Buck",
			"CUP_1Rnd_12Gauge_Pellets_No00_Buck",
			"CUP_1Rnd_12Gauge_Pellets_No00_Buck",
			"CUP_1Rnd_12Gauge_Pellets_No00_Buck",
			"CUP_1Rnd_12Gauge_Pellets_No00_Buck",
			"CUP_1Rnd_12Gauge_Pellets_No00_Buck",
			"CUP_1Rnd_12Gauge_Pellets_No00_Buck",
			"CUP_1Rnd_12Gauge_Pellets_No00_Buck",
			"CUP_1Rnd_12Gauge_Pellets_No00_Buck",
			"CUP_1Rnd_12Gauge_Pellets_No00_Buck",
			"CUP_1Rnd_12Gauge_Pellets_No00_Buck",
			"CUP_1Rnd_12Gauge_Pellets_No00_Buck",
			"CUP_1Rnd_12Gauge_Pellets_No00_Buck",
			"CUP_1Rnd_12Gauge_Pellets_No00_Buck",
			LOADOUT_MAGAZINES_FULL
		};
		respawnMagazines[]=
		{
			"CUP_1Rnd_12Gauge_Pellets_No00_Buck",
			"CUP_1Rnd_12Gauge_Pellets_No00_Buck",
			"CUP_1Rnd_12Gauge_Pellets_No00_Buck",
			"CUP_1Rnd_12Gauge_Pellets_No00_Buck",
			"CUP_1Rnd_12Gauge_Pellets_No00_Buck",
			"CUP_1Rnd_12Gauge_Pellets_No00_Buck",
			"CUP_1Rnd_12Gauge_Pellets_No00_Buck",
			"CUP_1Rnd_12Gauge_Pellets_No00_Buck",
			"CUP_1Rnd_12Gauge_Pellets_No00_Buck",
			"CUP_1Rnd_12Gauge_Pellets_No00_Buck",
			"CUP_1Rnd_12Gauge_Pellets_No00_Buck",
			"CUP_1Rnd_12Gauge_Pellets_No00_Buck",
			"CUP_1Rnd_12Gauge_Pellets_No00_Buck",
			"CUP_1Rnd_12Gauge_Pellets_No00_Buck",
			"CUP_1Rnd_12Gauge_Pellets_No00_Buck",
			"CUP_1Rnd_12Gauge_Pellets_No00_Buck",
			"CUP_1Rnd_12Gauge_Pellets_No00_Buck",
			"CUP_1Rnd_12Gauge_Pellets_No00_Buck",
			"CUP_1Rnd_12Gauge_Pellets_No00_Buck",
			"CUP_1Rnd_12Gauge_Pellets_No00_Buck",
			"CUP_1Rnd_12Gauge_Pellets_No00_Buck",
			"CUP_1Rnd_12Gauge_Pellets_No00_Buck",
			"CUP_1Rnd_12Gauge_Pellets_No00_Buck",
			"CUP_1Rnd_12Gauge_Pellets_No00_Buck",
			LOADOUT_MAGAZINES_FULL
		};
	};
	class SIL_STALKER_Bandit_Sharpshooter_F: SIL_STALKER_Bandit_Base_F
	{
		PREVIEW(SIL_STALKER_Bandit_Sharpshooter_F);
		displayName = "Sharpshooter";
		uniformClass = "SCE_Bandit_5";
		scope = 2;
		identityTypes[]=
		{
			"Male05ENG",
			"WhiteHead_07",
			"NoGlasses"
		};
		linkedItems[]=
		{
			"armst_Hood_closed_dolg1",
			"G_Balaclava_blk",
			"SCE_Sunrise_Bandit",
			LOADOUT_ITEMS_FULL
		};
		respawnLinkedItems[]=
		{
			"armst_Hood_closed_dolg1",
			"G_Balaclava_blk",
			"SCE_Sunrise_Bandit",
			LOADOUT_ITEMS_FULL
		};
		weapons[]=
		{
			"CUP_srifle_CZ550",
			LOADOUT_WEAPONS_DEFAULT
		};
		respawnWeapons[]=
		{
			"CUP_srifle_CZ550",
			LOADOUT_WEAPONS_DEFAULT
		};
		magazines[]=
		{
			"CUP_5x_22_LR_17_HMR_M",
			"CUP_5x_22_LR_17_HMR_M",
			"CUP_5x_22_LR_17_HMR_M",
			"CUP_5x_22_LR_17_HMR_M",
			"CUP_5x_22_LR_17_HMR_M",
			"CUP_5x_22_LR_17_HMR_M",
			"CUP_5x_22_LR_17_HMR_M",
			"CUP_5x_22_LR_17_HMR_M",
			"CUP_5x_22_LR_17_HMR_M",
			"CUP_5x_22_LR_17_HMR_M",
			"CUP_5x_22_LR_17_HMR_M",
			"CUP_5x_22_LR_17_HMR_M",
			LOADOUT_MAGAZINES_FULL
		};
		respawnMagazines[]=
		{
			"CUP_5x_22_LR_17_HMR_M",
			"CUP_5x_22_LR_17_HMR_M",
			"CUP_5x_22_LR_17_HMR_M",
			"CUP_5x_22_LR_17_HMR_M",
			"CUP_5x_22_LR_17_HMR_M",
			"CUP_5x_22_LR_17_HMR_M",
			"CUP_5x_22_LR_17_HMR_M",
			"CUP_5x_22_LR_17_HMR_M",
			"CUP_5x_22_LR_17_HMR_M",
			"CUP_5x_22_LR_17_HMR_M",
			"CUP_5x_22_LR_17_HMR_M",
			"CUP_5x_22_LR_17_HMR_M",
			LOADOUT_MAGAZINES_FULL
		};
	};
	class SIL_STALKER_Bandit_Autorifleman_F: SIL_STALKER_Bandit_Base_F
	{
		PREVIEW(SIL_STALKER_Bandit_Autorifleman_F);
		displayName = "Autorifleman";
		uniformClass = "SCE_Bandit_5";
		scope = 2;
		identityTypes[]=
		{
			"Male05ENG",
			"WhiteHead_07",
			"NoGlasses"
		};
		linkedItems[]=
		{
			"SCE_Exo_Helmet_Bandit",
			"SE_S10",
			"SCE_Exo2G_Bandit_2",
			LOADOUT_ITEMS_FULL
		};
		respawnLinkedItems[]=
		{
			"SCE_Exo_Helmet_Bandit",
			"SE_S10",
			"SCE_Exo2G_Bandit_2",
			LOADOUT_ITEMS_FULL
		};
		weapons[]=
		{
			"CUP_lmg_PKM",
			LOADOUT_WEAPONS_DEFAULT
		};
		respawnWeapons[]=
		{
			"CUP_lmg_PKM",
			LOADOUT_WEAPONS_DEFAULT
		};
		magazines[]=
		{
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
			LOADOUT_MAGAZINES_FULL
		};
		respawnMagazines[]=
		{
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
			LOADOUT_MAGAZINES_FULL
		};
	};