	// cfgVehicles

	class SIL_STALKER_Duty_Base_F: SIL_STALKER_Base_F
	{
		editorSubcategory = "SIL_STALKER_Subcategory_Duty_Men";
		scope = 1;
		side = FACTION_DUTY_SIDE; // 0 = OPFOR, 1 = BLUFOR, 2 = IND
		FACTION_DUTY;
		identityTypes[]=
		{
			"Male01ENG",
			"WhiteHead_01",
			"NoGlasses"
		};
	};

	class SIL_STALKER_Duty_Rifleman_1_F: SIL_STALKER_Duty_Base_F
	{
		PREVIEW(SIL_STALKER_Duty_Rifleman_1_F);
		displayName = "Rifleman";
		uniformClass = "SE_Assault_Fatigues_Duty";
		scope = 2;
		identityTypes[]=
		{
			"Male06ENG",
			"WhiteHead_04",
			"NoGlasses"
		};
		linkedItems[]=
		{
			"CUP_H_Ger_M92_Black",
			"SE_GP7",
			"SCE_V_SEVA_Duty",
			LOADOUT_ITEMS_FULL
		};
		respawnLinkedItems[]=
		{
			"CUP_H_Ger_M92_Black",
			"SE_GP7",
			"SCE_V_SEVA_Duty",
			LOADOUT_ITEMS_FULL
		};
		weapons[]=
		{
			"CUP_arifle_AK74M_GL",
			LOADOUT_WEAPONS_DEFAULT
		};
		respawnWeapons[]=
		{
			"CUP_arifle_AK74M_GL",
			LOADOUT_WEAPONS_DEFAULT
		};
		magazines[]=
		{
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_1Rnd_SmokeGreen_GP25_M",
			"CUP_1Rnd_SmokeGreen_GP25_M",
			"CUP_1Rnd_HE_GP25_M",
			"CUP_1Rnd_HE_GP25_M",
			LOADOUT_MAGAZINES_FULL
		};
		respawnMagazines[]=
		{
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_1Rnd_SmokeGreen_GP25_M",
			"CUP_1Rnd_SmokeGreen_GP25_M",
			"CUP_1Rnd_HE_GP25_M",
			"CUP_1Rnd_HE_GP25_M",
			LOADOUT_MAGAZINES_FULL
		};
	};
	class SIL_STALKER_Duty_Rifleman_2_F: SIL_STALKER_Duty_Base_F
	{
		PREVIEW(SIL_STALKER_Duty_Rifleman_2_F);
		displayName = "Rifleman (Alternate)";
		uniformClass = "SCE_Duty_CBRN";
		scope = 2;
		identityTypes[]=
		{
			"Male08ENG",
			"WhiteHead_03",
			"NoGlasses"
		};
		linkedItems[]=
		{
			"armst_Hood_mid_dolg1",
			"SCE_G_CN3P",
			"SCE_Sunrise_Duty",
			LOADOUT_ITEMS_FULL
		};
		respawnLinkedItems[]=
		{
			"armst_Hood_mid_dolg1",
			"SCE_G_CN3P",
			"SCE_Sunrise_Duty",
			LOADOUT_ITEMS_FULL
		};
		weapons[]=
		{
			"CUP_arifle_L85A2",
			LOADOUT_WEAPONS_DEFAULT
		};
		respawnWeapons[]=
		{
			"CUP_arifle_L85A2",
			LOADOUT_WEAPONS_DEFAULT
		};
		magazines[]=
		{
			"CUP_30Rnd_556x45_Stanag_L85",
			"CUP_30Rnd_556x45_Stanag_L85",
			"CUP_30Rnd_556x45_Stanag_L85",
			"CUP_30Rnd_556x45_Stanag_L85",
			"CUP_30Rnd_556x45_Stanag_L85",
			"CUP_30Rnd_556x45_Stanag_L85",
			LOADOUT_MAGAZINES_FULL
		};
		respawnMagazines[]=
		{
			"CUP_30Rnd_556x45_Stanag_L85",
			"CUP_30Rnd_556x45_Stanag_L85",
			"CUP_30Rnd_556x45_Stanag_L85",
			"CUP_30Rnd_556x45_Stanag_L85",
			"CUP_30Rnd_556x45_Stanag_L85",
			"CUP_30Rnd_556x45_Stanag_L85",
			LOADOUT_MAGAZINES_FULL
		};
	};
	class SIL_STALKER_Duty_Rifleman_Light_F: SIL_STALKER_Duty_Base_F
	{
		PREVIEW(SIL_STALKER_Duty_Rifleman_Light_F);
		displayName = "Rifleman (Light)";
		uniformClass = "SCE_Duty_2";
		scope = 2;
		identityTypes[]=
		{
			"Male03ENG",
			"WhiteHead_01",
			"NoGlasses"
		};
		linkedItems[]=
		{
			"armst_Hood_closed_dolg1",
			"CUP_RUS_Balaclava_blk",
			"SCE_Sunrise_Duty",
			LOADOUT_ITEMS_FULL
		};
		respawnLinkedItems[]=
		{
			"armst_Hood_closed_dolg1",
			"CUP_RUS_Balaclava_blk",
			"SCE_Sunrise_Duty",
			LOADOUT_ITEMS_FULL
		};
		weapons[]=
		{
			"CUP_arifle_OTS14_GROZA_GL",
			LOADOUT_WEAPONS_DEFAULT
		};
		respawnWeapons[]=
		{
			"CUP_arifle_OTS14_GROZA_GL",
			LOADOUT_WEAPONS_DEFAULT
		};
		magazines[]=
		{
			"CUP_20Rnd_9x39_SP5_GROZA_M",
			"CUP_20Rnd_9x39_SP5_GROZA_M",
			"CUP_20Rnd_9x39_SP5_GROZA_M",
			"CUP_20Rnd_9x39_SP5_GROZA_M",
			"CUP_20Rnd_9x39_SP5_GROZA_M",
			"CUP_1Rnd_HE_GP25_M",
			LOADOUT_MAGAZINES_FULL
		};
		respawnMagazines[]=
		{
			"CUP_20Rnd_9x39_SP5_GROZA_M",
			"CUP_20Rnd_9x39_SP5_GROZA_M",
			"CUP_20Rnd_9x39_SP5_GROZA_M",
			"CUP_20Rnd_9x39_SP5_GROZA_M",
			"CUP_20Rnd_9x39_SP5_GROZA_M",
			"CUP_1Rnd_HE_GP25_M",
			LOADOUT_MAGAZINES_FULL
		};
	};
	class SIL_STALKER_Duty_Medic_F: SIL_STALKER_Duty_Base_F
	{
		PREVIEW(SIL_STALKER_Duty_Medic_F);
		displayName = "Medic";
		uniformClass = "SCE_Duty_CBRN";
		scope = 2;
		backpack = "CUP_B_USPack_Black";
		UNIT_ROLE_MEDIC;
		identityTypes[]=
		{
			"Male08ENG",
			"WhiteHead_07",
			"NoGlasses"
		};
		linkedItems[]=
		{
			"armst_Hood_full_dolg1",
			"CUP_FR_NeckScarf3",
			"SCE_V_SEVA_Duty",
			LOADOUT_ITEMS_FULL
		};
		respawnLinkedItems[]=
		{
			"armst_Hood_full_dolg1",
			"CUP_FR_NeckScarf3",
			"SCE_V_SEVA_Duty",
			LOADOUT_ITEMS_FULL
		};
		weapons[]=
		{
			"CUP_arifle_AS_VAL",
			LOADOUT_WEAPONS_DEFAULT
		};
		respawnWeapons[]=
		{
			"CUP_arifle_AS_VAL",
			LOADOUT_WEAPONS_DEFAULT
		};
		magazines[]=
		{
			"CUP_20Rnd_9x39_SP5_VSS_M",
			"CUP_20Rnd_9x39_SP5_VSS_M",
			"CUP_20Rnd_9x39_SP5_VSS_M",
			"CUP_20Rnd_9x39_SP5_VSS_M",
			"CUP_20Rnd_9x39_SP5_VSS_M",
			"CUP_20Rnd_9x39_SP5_VSS_M",
			LOADOUT_MAGAZINES_FULL
		};
		respawnMagazines[]=
		{
			"CUP_20Rnd_9x39_SP5_VSS_M",
			"CUP_20Rnd_9x39_SP5_VSS_M",
			"CUP_20Rnd_9x39_SP5_VSS_M",
			"CUP_20Rnd_9x39_SP5_VSS_M",
			"CUP_20Rnd_9x39_SP5_VSS_M",
			"CUP_20Rnd_9x39_SP5_VSS_M",
			LOADOUT_MAGAZINES_FULL
		};
	};
	class SIL_STALKER_Duty_Sharpshooter_F: SIL_STALKER_Duty_Base_F
	{
		PREVIEW(SIL_STALKER_Duty_Sharpshooter_F);
		displayName = "Sharpshooter";
		uniformClass = "SCE_Duty_2";
		scope = 2;
		identityTypes[]=
		{
			"Male09ENG",
			"WhiteHead_05",
			"NoGlasses"
		};
		linkedItems[]=
		{
			"armst_Hood_mid_dolg1",
			"SCE_G_CN2F",
			"SCE_Sunrise_Duty",
			LOADOUT_ITEMS_FULL
		};
		respawnLinkedItems[]=
		{
			"armst_Hood_mid_dolg1",
			"SCE_G_CN2F",
			"SCE_Sunrise_Duty",
			LOADOUT_ITEMS_FULL
		};
		weapons[]=
		{
			"CUP_srifle_SVD_top_rail",
			LOADOUT_WEAPONS_DEFAULT
		};
		respawnWeapons[]=
		{
			"CUP_srifle_SVD_top_rail",
			LOADOUT_WEAPONS_DEFAULT
		};
		magazines[]=
		{
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			LOADOUT_MAGAZINES_FULL
		};
		respawnMagazines[]=
		{
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			LOADOUT_MAGAZINES_FULL
		};
	};
	class SIL_STALKER_Duty_Engineer_F: SIL_STALKER_Duty_Base_F
	{
		PREVIEW(SIL_STALKER_Duty_Engineer_F);
		displayName = "Engineer";
		uniformClass = "SE_Assault_Fatigues_Duty";
		scope = 2;
		backpack = "CUP_B_AssaultPack_Black";
		UNIT_ROLE_ENGINEER;
		identityTypes[]=
		{
			"Male09ENG",
			"WhiteHead_05",
			"NoGlasses"
		};
		linkedItems[]=
		{
			"SCE_Exo_Helmet_Duty",
			"SE_GP7",
			"SCE_Exo2G_Duty_1",
			LOADOUT_ITEMS_FULL
		};
		respawnLinkedItems[]=
		{
			"SCE_Exo_Helmet_Duty",
			"SE_GP7",
			"SCE_Exo2G_Duty_1",
			LOADOUT_ITEMS_FULL
		};
		weapons[]=
		{
			"CUP_smg_vityaz_vfg",
			LOADOUT_WEAPONS_DEFAULT
		};
		respawnWeapons[]=
		{
			"CUP_smg_vityaz_vfg",
			LOADOUT_WEAPONS_DEFAULT
		};
		magazines[]=
		{
			"CUP_30Rnd_9x19AP_Vityaz",
			"CUP_30Rnd_9x19AP_Vityaz",
			"CUP_30Rnd_9x19AP_Vityaz",
			"CUP_30Rnd_9x19AP_Vityaz",
			"CUP_30Rnd_9x19AP_Vityaz",
			"CUP_30Rnd_9x19AP_Vityaz",
			LOADOUT_MAGAZINES_FULL
		};
		respawnMagazines[]=
		{
			"CUP_30Rnd_9x19AP_Vityaz",
			"CUP_30Rnd_9x19AP_Vityaz",
			"CUP_30Rnd_9x19AP_Vityaz",
			"CUP_30Rnd_9x19AP_Vityaz",
			"CUP_30Rnd_9x19AP_Vityaz",
			"CUP_30Rnd_9x19AP_Vityaz",
			LOADOUT_MAGAZINES_FULL
		};
	};
	class SIL_STALKER_Duty_Autorifleman_F: SIL_STALKER_Duty_Base_F
	{
		PREVIEW(SIL_STALKER_Duty_Autorifleman_F);
		displayName = "Autorifleman";
		uniformClass = "SE_Assault_Fatigues_Duty";
		scope = 2;
		backpack = "CUP_B_AssaultPack_Black";
		identityTypes[]=
		{
			"Male09ENG",
			"WhiteHead_05",
			"NoGlasses"
		};
		linkedItems[]=
		{
			"SCE_Exo_Helmet_Duty",
			"SE_GP7",
			"SCE_Exo2G_Duty_1",
			LOADOUT_ITEMS_FULL
		};
		respawnLinkedItems[]=
		{
			"SCE_Exo_Helmet_Duty",
			"SE_GP7",
			"SCE_Exo2G_Duty_1",
			LOADOUT_ITEMS_FULL
		};
		weapons[]=
		{
			"CUP_lmg_PKM_B50_vfg",
			LOADOUT_WEAPONS_DEFAULT
		};
		respawnWeapons[]=
		{
			"CUP_lmg_PKM_B50_vfg",
			LOADOUT_WEAPONS_DEFAULT
		};
		magazines[]=
		{
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
			LOADOUT_MAGAZINES_FULL
		};
		respawnMagazines[]=
		{
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
			LOADOUT_MAGAZINES_FULL
		};
	};

	/* SEVA Units */
	class SIL_STALKER_Duty_SEVA_Base_F: SIL_STALKER_Duty_Base_F
	{
		uniformClass = "SCE_Duty_CBRN";
		backpack = "SCE_B_SEVA_Duty";
		editorSubcategory = "SIL_STALKER_Subcategory_Duty_Men_SEVA";
		scope = 1;
		linkedItems[]=
		{
			"SCE_H_SEVA_Duty",
			"SCE_G_SEVA_HELMET_VISOR",
			"SCE_V_SEVA_Duty",
			LOADOUT_ITEMS_FULL
		};
		respawnLinkedItems[]=
		{
			"SCE_H_SEVA_Duty",
			"SCE_G_SEVA_HELMET_VISOR",
			"SCE_V_SEVA_Duty",
			LOADOUT_ITEMS_FULL
		};
	};
	class SIL_STALKER_Duty_SEVA_Rifleman_1_F: SIL_STALKER_Duty_SEVA_Base_F
	{
		PREVIEW(SIL_STALKER_Duty_SEVA_Rifleman_1_F);
		displayName = "Rifleman";
		scope = 2;
		identityTypes[]=
		{
			"Male02ENG",
			"WhiteHead_04",
			"NoGlasses"
		};
		weapons[]=
		{
			"CUP_arifle_AK74M",
			LOADOUT_WEAPONS_DEFAULT
		};
		respawnWeapons[]=
		{
			"CUP_arifle_AK74M",
			LOADOUT_WEAPONS_DEFAULT
		};
		magazines[]=
		{
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			LOADOUT_MAGAZINES_FULL
		};
		respawnMagazines[]=
		{
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			LOADOUT_MAGAZINES_FULL
		};
	};
	class SIL_STALKER_Duty_SEVA_Rifleman_2_F: SIL_STALKER_Duty_SEVA_Base_F
	{
		PREVIEW(SIL_STALKER_Duty_SEVA_Rifleman_2_F);
		displayName = "Rifleman (Alternate)";
		scope = 2;
		identityTypes[]=
		{
			"Male02ENG",
			"WhiteHead_04",
			"NoGlasses"
		};
		weapons[]=
		{
			"CUP_arifle_L85A2",
			LOADOUT_WEAPONS_DEFAULT
		};
		respawnWeapons[]=
		{
			"CUP_arifle_L85A2",
			LOADOUT_WEAPONS_DEFAULT
		};
		magazines[]=
		{
			"CUP_30Rnd_556x45_Stanag_L85",
			"CUP_30Rnd_556x45_Stanag_L85",
			"CUP_30Rnd_556x45_Stanag_L85",
			"CUP_30Rnd_556x45_Stanag_L85",
			"CUP_30Rnd_556x45_Stanag_L85",
			"CUP_30Rnd_556x45_Stanag_L85",
			LOADOUT_MAGAZINES_FULL
		};
		respawnMagazines[]=
		{
			"CUP_30Rnd_556x45_Stanag_L85",
			"CUP_30Rnd_556x45_Stanag_L85",
			"CUP_30Rnd_556x45_Stanag_L85",
			"CUP_30Rnd_556x45_Stanag_L85",
			"CUP_30Rnd_556x45_Stanag_L85",
			"CUP_30Rnd_556x45_Stanag_L85",
			LOADOUT_MAGAZINES_FULL
		};
	};
	class SIL_STALKER_Duty_SEVA_Rifleman_Light_F: SIL_STALKER_Duty_SEVA_Base_F
	{
		PREVIEW(SIL_STALKER_Duty_SEVA_Rifleman_Light_F);
		displayName = "Rifleman (Light)";
		scope = 2;
		identityTypes[]=
		{
			"Male02ENG",
			"WhiteHead_04",
			"NoGlasses"
		};
		weapons[]=
		{
			"CUP_arifle_OTS14_GROZA_GL",
			LOADOUT_WEAPONS_DEFAULT
		};
		respawnWeapons[]=
		{
			"CUP_arifle_OTS14_GROZA_GL",
			LOADOUT_WEAPONS_DEFAULT
		};
		magazines[]=
		{
			"CUP_20Rnd_9x39_SP5_GROZA_M",
			"CUP_20Rnd_9x39_SP5_GROZA_M",
			"CUP_20Rnd_9x39_SP5_GROZA_M",
			"CUP_20Rnd_9x39_SP5_GROZA_M",
			"CUP_20Rnd_9x39_SP5_GROZA_M",
			"CUP_1Rnd_HE_GP25_M",
			LOADOUT_MAGAZINES_FULL
		};
		respawnMagazines[]=
		{
			"CUP_20Rnd_9x39_SP5_GROZA_M",
			"CUP_20Rnd_9x39_SP5_GROZA_M",
			"CUP_20Rnd_9x39_SP5_GROZA_M",
			"CUP_20Rnd_9x39_SP5_GROZA_M",
			"CUP_20Rnd_9x39_SP5_GROZA_M",
			"CUP_1Rnd_HE_GP25_M",
			LOADOUT_MAGAZINES_FULL
		};
	};
	class SIL_STALKER_Duty_SEVA_Medic_F: SIL_STALKER_Duty_SEVA_Base_F
	{
		PREVIEW(SIL_STALKER_Duty_SEVA_Medic_F);
		displayName = "Medic";
		scope = 2;
		UNIT_ROLE_MEDIC;
		identityTypes[]=
		{
			"Male02ENG",
			"WhiteHead_04",
			"NoGlasses"
		};
		weapons[]=
		{
			"CUP_arifle_AS_VAL",
			LOADOUT_WEAPONS_DEFAULT
		};
		respawnWeapons[]=
		{
			"CUP_arifle_AS_VAL",
			LOADOUT_WEAPONS_DEFAULT
		};
		magazines[]=
		{
			"CUP_20Rnd_9x39_SP5_VSS_M",
			"CUP_20Rnd_9x39_SP5_VSS_M",
			"CUP_20Rnd_9x39_SP5_VSS_M",
			"CUP_20Rnd_9x39_SP5_VSS_M",
			"CUP_20Rnd_9x39_SP5_VSS_M",
			"CUP_20Rnd_9x39_SP5_VSS_M",
			LOADOUT_MAGAZINES_FULL
		};
		respawnMagazines[]=
		{
			"CUP_20Rnd_9x39_SP5_VSS_M",
			"CUP_20Rnd_9x39_SP5_VSS_M",
			"CUP_20Rnd_9x39_SP5_VSS_M",
			"CUP_20Rnd_9x39_SP5_VSS_M",
			"CUP_20Rnd_9x39_SP5_VSS_M",
			"CUP_20Rnd_9x39_SP5_VSS_M",
			LOADOUT_MAGAZINES_FULL
		};
	};

	/* Exo Units */
	class SIL_STALKER_Duty_Exo_Base_F: SIL_STALKER_Duty_Base_F
	{
		uniformClass = "SE_Assault_Fatigues_Duty";
		editorSubcategory = "SIL_STALKER_Subcategory_Duty_Men_Exo";
		scope = 1;
		linkedItems[]=
		{
			"SCE_Exo_Helmet_Duty",
			"SE_GP7",
			"SCE_Exo2G_Duty_2",
			LOADOUT_ITEMS_FULL
		};
		respawnLinkedItems[]=
		{
			"SCE_Exo_Helmet_Duty",
			"SE_GP7",
			"SCE_Exo2G_Duty_2",
			LOADOUT_ITEMS_FULL
		};
	};
	class SIL_STALKER_Duty_Exo_Rifleman_1_F: SIL_STALKER_Duty_Exo_Base_F
	{
		PREVIEW(SIL_STALKER_Duty_Exo_Rifleman_1_F);
		displayName = "Rifleman";
		scope = 2;
		weapons[]=
		{
			"CUP_arifle_AK74M",
			LOADOUT_WEAPONS_DEFAULT
		};
		respawnWeapons[]=
		{
			"CUP_arifle_AK74M",
			LOADOUT_WEAPONS_DEFAULT
		};
		magazines[]=
		{
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			LOADOUT_MAGAZINES_FULL
		};
		respawnMagazines[]=
		{
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			LOADOUT_MAGAZINES_FULL
		};
	};
	class SIL_STALKER_Duty_Exo_Rifleman_2_F: SIL_STALKER_Duty_Exo_Base_F
	{
		PREVIEW(SIL_STALKER_Duty_Exo_Rifleman_2_F);
		displayName = "Rifleman (Alternate)";
		scope = 2;
		weapons[]=
		{
			"CUP_arifle_L85A2",
			LOADOUT_WEAPONS_DEFAULT
		};
		respawnWeapons[]=
		{
			"CUP_arifle_L85A2",
			LOADOUT_WEAPONS_DEFAULT
		};
		magazines[]=
		{
			"CUP_30Rnd_556x45_Stanag_L85",
			"CUP_30Rnd_556x45_Stanag_L85",
			"CUP_30Rnd_556x45_Stanag_L85",
			"CUP_30Rnd_556x45_Stanag_L85",
			"CUP_30Rnd_556x45_Stanag_L85",
			"CUP_30Rnd_556x45_Stanag_L85",
			LOADOUT_MAGAZINES_FULL
		};
		respawnMagazines[]=
		{
			"CUP_30Rnd_556x45_Stanag_L85",
			"CUP_30Rnd_556x45_Stanag_L85",
			"CUP_30Rnd_556x45_Stanag_L85",
			"CUP_30Rnd_556x45_Stanag_L85",
			"CUP_30Rnd_556x45_Stanag_L85",
			"CUP_30Rnd_556x45_Stanag_L85",
			LOADOUT_MAGAZINES_FULL
		};
	};