	// cfgVehicles

	class SIL_STALKER_IPSF_Base_F: SIL_STALKER_Base_F
	{
		editorSubcategory = "SIL_STALKER_Subcategory_IPSF_Men";
		uniformClass = "SIL_STALKER_U_IPSF_Ghillie_Top";
		scope = 1;
		side = FACTION_IPSF_SIDE; // 0 = OPFOR, 1 = BLUFOR, 2 = IND
		FACTION_IPSF;
		identityTypes[]=
		{
			"Male01ENG",
			"WhiteHead_01",
			"NoGlasses"
		};
	};

	class SIL_STALKER_IPSF_Rifleman_1_F: SIL_STALKER_IPSF_Base_F
	{
		PREVIEW(SIL_STALKER_IPSF_Rifleman_1_F);
		displayName = "Rifleman";
		scope = 2;
		backpack = "CUP_B_ACRPara_m95";
		identityTypes[]=
		{
			"Male03ENG",
			"WhiteHead_04",
			"NoGlasses"
		};
		linkedItems[]=
		{
			"CAU_G_CBRN_m04_blk_hood",
			"CUP_V_O_RUS_RPS_Smersh_AK_ModernOlive",
			LOADOUT_ITEMS_FULL
		};
		respawnLinkedItems[]=
		{
			"CAU_G_CBRN_m04_blk_hood",
			"CUP_V_O_RUS_RPS_Smersh_AK_ModernOlive",
			LOADOUT_ITEMS_FULL
		};
		weapons[]=
		{
			"CUP_arifle_AK74M_1p63",
			LOADOUT_WEAPONS_DEFAULT
		};
		respawnWeapons[]=
		{
			"CUP_arifle_AK74M_1p63",
			LOADOUT_WEAPONS_DEFAULT
		};
		magazines[]=
		{
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			LOADOUT_MAGAZINES_FULL
		};
		respawnMagazines[]=
		{
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			LOADOUT_MAGAZINES_FULL
		};
	};
	class SIL_STALKER_IPSF_Rifleman_2_F: SIL_STALKER_IPSF_Base_F
	{
		PREVIEW(SIL_STALKER_IPSF_Rifleman_2_F);
		displayName = "Rifleman (Alternate)";
		scope = 2;
		backpack = "CUP_B_Kombat_Olive";
		identityTypes[]=
		{
			"Male04ENG",
			"WhiteHead_07",
			"NoGlasses"
		};
		linkedItems[]=
		{
			"SE_Respirator",
			"CUP_V_B_RRV_Scout",
			LOADOUT_ITEMS_FULL
		};
		respawnLinkedItems[]=
		{
			"SE_Respirator",
			"CUP_V_B_RRV_Scout",
			LOADOUT_ITEMS_FULL
		};
		weapons[]=
		{
			"CUP_arifle_AS_VAL",
			LOADOUT_WEAPONS_DEFAULT
		};
		respawnWeapons[]=
		{
			"CUP_arifle_AS_VAL",
			LOADOUT_WEAPONS_DEFAULT
		};
		magazines[]=
		{
			"CUP_30Rnd_9x39_SP5_VIKHR_M",
			"CUP_30Rnd_9x39_SP5_VIKHR_M",
			"CUP_30Rnd_9x39_SP5_VIKHR_M",
			"CUP_30Rnd_9x39_SP5_VIKHR_M",
			"CUP_30Rnd_9x39_SP5_VIKHR_M",
			"CUP_30Rnd_9x39_SP5_VIKHR_M",
			LOADOUT_MAGAZINES_FULL
		};
		respawnMagazines[]=
		{
			"CUP_30Rnd_9x39_SP5_VIKHR_M",
			"CUP_30Rnd_9x39_SP5_VIKHR_M",
			"CUP_30Rnd_9x39_SP5_VIKHR_M",
			"CUP_30Rnd_9x39_SP5_VIKHR_M",
			"CUP_30Rnd_9x39_SP5_VIKHR_M",
			"CUP_30Rnd_9x39_SP5_VIKHR_M",
			LOADOUT_MAGAZINES_FULL
		};
	};
	class SIL_STALKER_IPSF_Rifleman_Light_F: SIL_STALKER_IPSF_Base_F
	{
		PREVIEW(SIL_STALKER_IPSF_Rifleman_Light_F);
		displayName = "Rifleman (Light)";
		scope = 2;
		backpack = "CUP_B_Kombat_Olive";
		identityTypes[]=
		{
			"Male06ENG",
			"WhiteHead_09",
			"NoGlasses"
		};
		linkedItems[]=
		{
			"SCE_G_CN3P",
			"CUP_V_RUS_Smersh_New_Light_Spectre",
			LOADOUT_ITEMS_FULL
		};
		respawnLinkedItems[]=
		{
			"SCE_G_CN3P",
			"CUP_V_RUS_Smersh_New_Light_Spectre",
			LOADOUT_ITEMS_FULL
		};
		weapons[]=
		{
			"CUP_arifle_AKS74UN_kobra_snds",
			LOADOUT_WEAPONS_DEFAULT
		};
		respawnWeapons[]=
		{
			"CUP_arifle_AKS74UN_kobra_snds",
			LOADOUT_WEAPONS_DEFAULT
		};
		magazines[]=
		{
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			LOADOUT_MAGAZINES_FULL
		};
		respawnMagazines[]=
		{
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			LOADOUT_MAGAZINES_FULL
		};
	};
	class SIL_STALKER_IPSF_Medic_F: SIL_STALKER_IPSF_Base_F
	{
		PREVIEW(SIL_STALKER_IPSF_Medic_F);
		displayName = "Medic";
		scope = 2;
		backpack = "CUP_B_RUS_Backpack";
		UNIT_ROLE_MEDIC;
		identityTypes[]=
		{
			"Male06ENG",
			"WhiteHead_09",
			"NoGlasses"
		};
		linkedItems[]=
		{
			"CUP_FR_NeckScarf2",
			"CUP_V_B_RRV_Medic",
			LOADOUT_ITEMS_FULL
		};
		respawnLinkedItems[]=
		{
			"CUP_FR_NeckScarf2",
			"CUP_V_B_RRV_Medic",
			LOADOUT_ITEMS_FULL
		};
		weapons[]=
		{
			"CUP_arifle_AKS74U",
			LOADOUT_WEAPONS_DEFAULT
		};
		respawnWeapons[]=
		{
			"CUP_arifle_AKS74U",
			LOADOUT_WEAPONS_DEFAULT
		};
		magazines[]=
		{
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			LOADOUT_MAGAZINES_FULL
		};
		respawnMagazines[]=
		{
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			LOADOUT_MAGAZINES_FULL
		};
	};
	class SIL_STALKER_IPSF_Sharpshooter_F: SIL_STALKER_IPSF_Base_F
	{
		PREVIEW(SIL_STALKER_IPSF_Sharpshooter_F);
		displayName = "Sharpshooter";
		scope = 2;
		backpack = "SE_Satchel_Bag";
		identityTypes[]=
		{
			"Male09ENG",
			"WhiteHead_02",
			"NoGlasses"
		};
		linkedItems[]=
		{
			"SCE_G_CN2F",
			"CUP_V_O_RUS_RPS_Smersh_SVD_ModernOlive",
			LOADOUT_ITEMS_FULL
		};
		respawnLinkedItems[]=
		{
			"SCE_G_CN2F",
			"CUP_V_O_RUS_RPS_Smersh_SVD_ModernOlive",
			LOADOUT_ITEMS_FULL
		};
		weapons[]=
		{
			"CUP_srifle_SVD_pso",
			LOADOUT_WEAPONS_DEFAULT
		};
		respawnWeapons[]=
		{
			"CUP_srifle_SVD_pso",
			LOADOUT_WEAPONS_DEFAULT
		};
		magazines[]=
		{
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			LOADOUT_MAGAZINES_FULL
		};
		respawnMagazines[]=
		{
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			LOADOUT_MAGAZINES_FULL
		};
	};
	class SIL_STALKER_IPSF_Pilot_F: SIL_STALKER_IPSF_Base_F
	{
		PREVIEW(SIL_STALKER_IPSF_Pilot_F);
		displayName = "Pilot";
		uniformClass = "SIL_STALKER_U_USArmy_PilotOverall";
		scope = 2;
		identityTypes[]=
		{
			"Male09ENG",
			"WhiteHead_02",
			"NoGlasses"
		};
		linkedItems[]=
		{
			"H_PilotHelmetHeli_O",
			"CUP_V_B_PilotVest",
			LOADOUT_ITEMS_FULL
		};
		respawnLinkedItems[]=
		{
			"H_PilotHelmetHeli_O",
			"CUP_V_B_PilotVest",
			LOADOUT_ITEMS_FULL
		};
		weapons[]=
		{
			LOADOUT_WEAPONS_DEFAULT
		};
		respawnWeapons[]=
		{
			LOADOUT_WEAPONS_DEFAULT
		};
		magazines[]={};
		respawnMagazines[]={};
	};